name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secretpassword
          POSTGRES_DB: riasec-db

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install prisma and test
        run: |
          npm install
          npm run migrate deploy
          # npm run test
        env:
          CI: true
          HOST: localhost
          DATABASE_URL: postgres://postgres:secretpassword@localhost:5432/riasec-db
          PORT: 3000
          # PGHOST: localhost
          # PGPORT: 5432
          # PGUSER: postgres
          # PGPASSWORD: secretpassword
          # PGDATABASE: riasec-db
          ACCESS_TOKEN_KEY: secret
          REFRESH_TOKEN_KEY: terces
          ACCESS_TOKEN_AGE: 3600
